remove fflush() call before exit()
the buffer is flushed anyways at exit() and fixes compile error with
gcc14:

    pico/carthw/svp/compiler.c: In function 'ssp_translate_block':
    pico/carthw/svp/compiler.c:1800:24: error: passing argument 1 of 'rfflush' from incompatible pointer type [-Wincompatible-pointer-types]
     1800 |                 fflush(stdout);
          |                        ^~~~~~
          |                        |
          |                        FILE *
    In file included from ./pico/pico_port.h:12,
                     from ./pico/pico_int.h:15,
                     from pico/carthw/svp/compiler.c:9:
    platform/libretro/libretro-common/include/streams/file_stream_transforms.h:89:25: note: expected 'RFILE *' but argument is of type 'FILE *'
       89 | int64_t rfflush(RFILE * stream);
          |                 ~~~~~~~~^~~~~~

this error presents itself when building the libretro core, so this
could be also solved by wrapping the call to fflush():

    #ifndef __LIBRETRO__
    		fflush(stdout);
    #else
                fflush((RFILE *)stdout);
    #endif